version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    # command:
      # - --encryptionEnv #optional
      # - ENCRYPTION #optional
    # environment:
      # ENCRYPTION: example #optional
    ports:
      - "8020:8020"
    volumes:
      - ./Tests/pb_data:/pb_data
