//
//  Record.swift
//  PocketBase
//
//  Created by Brianna Zamora on 8/5/24.
//

import Foundation

public protocol Record: Identifiable, Decodable, EncodableWithConfiguration, Sendable, Equatable, Hashable where EncodingConfiguration == PocketBase.EncodingConfiguration {
    /// 15 characters string to store as record ID.
    ///
    /// If not set, it will be auto generated when it is created.
    var id: String { get }
    var collectionId: String { get }
    var collectionName: String { get }
    var created: Date { get }
    var updated: Date { get }

    static var collection: String { get }

    static var relations: [String: any Record.Type] { get }

    /// The names of file fields in this record type.
    ///
    /// File fields are marked with `@FileField` and store filename strings.
    /// This property is automatically generated by the `@BaseCollection` or
    /// `@AuthCollection` macros.
    static var fileFields: [String] { get }

    /// Extracts any pending file uploads from this record's file fields.
    ///
    /// This method inspects all `@FileField` properties and returns a payload
    /// containing any pending uploads (files that haven't been uploaded to the
    /// server yet).
    ///
    /// This method is automatically generated by the `@BaseCollection` or
    /// `@AuthCollection` macros.
    func pendingFileUploads() -> FileUploadPayload

    /// Extracts existing filenames from this record's file fields.
    ///
    /// This method inspects all `@FileField` properties and returns a dictionary
    /// mapping field names to arrays of existing filenames (files already on the server).
    /// This is used during updates to preserve existing files when adding new ones.
    ///
    /// This method is automatically generated by the `@BaseCollection` or
    /// `@AuthCollection` macros.
    func existingFilenames() -> [String: [String]]
}

extension Record {
    /// Returns `true` if this record has any pending file uploads.
    ///
    /// Use this to check if a record needs multipart/form-data encoding.
    public var hasPendingFileUploads: Bool {
        !pendingFileUploads().isEmpty
    }
}

public protocol BaseRecord: Record {}
